In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("rough.csv")

df.drop(["Unnamed: 0"],axis="columns",inplace=True)

In [3]:
df.drop(["Unnamed: 0.1"],axis="columns",inplace=True)
df

,Annual Rental Value,Extent of Site (Sq.Yds),Lift,Toilets,Water Tap,Electricity,Attached Bathroom,Water Harvesting,cable connection,Central Government 50%,...,Revenue Ward 67.1,Revenue Ward 68.1,Revenue Ward 69.1,Revenue Ward 7.1,Revenue Ward 70.1,Revenue Ward 71.1,Revenue Ward 72.1,Revenue Ward 73.1,Revenue Ward 8.1,Revenue Ward 9.1
0,3323,0.00,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3592,531.65,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10585,0.00,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9185,79.20,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,8725,240.00,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4515,3002,493.95,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4516,3481,552.73,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4517,3610,111.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4518,10644,0.00,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4519,6746,511.35,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dff=df.copy()
dff

,Annual Rental Value,Extent of Site (Sq.Yds),Lift,Toilets,Water Tap,Electricity,Attached Bathroom,Water Harvesting,cable connection,Central Government 50%,...,Revenue Ward 67.1,Revenue Ward 68.1,Revenue Ward 69.1,Revenue Ward 7.1,Revenue Ward 70.1,Revenue Ward 71.1,Revenue Ward 72.1,Revenue Ward 73.1,Revenue Ward 8.1,Revenue Ward 9.1
0,3323,0.00,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3592,531.65,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10585,0.00,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9185,79.20,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,8725,240.00,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4515,3002,493.95,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4516,3481,552.73,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4517,3610,111.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4518,10644,0.00,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4519,6746,511.35,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
dff1=dff.sort_values(["Extent of Site (Sq.Yds)","Annual Rental Value"],0).copy()
dff1

C:\Users\anura\AppData\Local\Temp/ipykernel_4556/1257445673.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_values except for the argument 'by' will be keyword-only
  dff1=dff.sort_values(["Extent of Site (Sq.Yds)","Annual Rental Value"],0).copy()

,Annual Rental Value,Extent of Site (Sq.Yds),Lift,Toilets,Water Tap,Electricity,Attached Bathroom,Water Harvesting,cable connection,Central Government 50%,...,Revenue Ward 67.1,Revenue Ward 68.1,Revenue Ward 69.1,Revenue Ward 7.1,Revenue Ward 70.1,Revenue Ward 71.1,Revenue Ward 72.1,Revenue Ward 73.1,Revenue Ward 8.1,Revenue Ward 9.1
2443,0,0.0,0,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3103,0,0.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3201,0,0.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3202,0,0.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3203,0,0.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2742,4533,21021.0,0,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2739,4855,21021.0,0,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3575,5090,21021.0,0,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4104,9183,113627.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3868,12027,113627.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
dff1.to_csv("rough.csv")